/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as InvitationsTokenRouteImport } from './routes/invitations/$token'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as NotesNoteIdRouteImport } from './routes/notes/$noteId'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsAuthRouteImport } from './routes/settings/auth'
import { Route as SettingsDangerRouteImport } from './routes/settings/danger'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsUsageRouteImport } from './routes/settings/usage'
import { Route as StorageSplatRouteImport } from './routes/storage.$'
import { Route as WSlugRouteImport } from './routes/w/$slug'
import { Route as WorkspacesNewRouteImport } from './routes/workspaces/new'
import { Route as AuthCallbackProviderRouteImport } from './routes/auth/callback.$provider'
import { Route as DevOauthAuthorizeRouteImport } from './routes/dev/oauth/authorize'
import { Route as WorkspacesWorkspaceIdSettingsRouteRouteImport } from './routes/workspaces/$workspaceId/settings/route'
import { Route as WorkspacesWorkspaceIdNotesIndexRouteImport } from './routes/workspaces/$workspaceId/notes/index'
import { Route as WorkspacesWorkspaceIdNotesNoteIdRouteImport } from './routes/workspaces/$workspaceId/notes/$noteId'
import { Route as WorkspacesWorkspaceIdSettingsDangerRouteImport } from './routes/workspaces/$workspaceId/settings/danger'
import { Route as WorkspacesWorkspaceIdSettingsGeneralRouteImport } from './routes/workspaces/$workspaceId/settings/general'
import { Route as WorkspacesWorkspaceIdSettingsMembersRouteImport } from './routes/workspaces/$workspaceId/settings/members'
import { Route as WorkspacesWorkspaceIdSettingsPublishRouteImport } from './routes/workspaces/$workspaceId/settings/publish'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsTokenRoute = InvitationsTokenRouteImport.update({
  id: '/invitations/$token',
  path: '/invitations/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAuthRoute = SettingsAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsDangerRoute = SettingsDangerRouteImport.update({
  id: '/danger',
  path: '/danger',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsUsageRoute = SettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const StorageSplatRoute = StorageSplatRouteImport.update({
  id: '/storage/$',
  path: '/storage/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugRoute = WSlugRouteImport.update({
  id: '/w/$slug',
  path: '/w/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesNewRoute = WorkspacesNewRouteImport.update({
  id: '/workspaces/new',
  path: '/workspaces/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackProviderRoute = AuthCallbackProviderRouteImport.update({
  id: '/auth/callback/$provider',
  path: '/auth/callback/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const DevOauthAuthorizeRoute = DevOauthAuthorizeRouteImport.update({
  id: '/dev/oauth/authorize',
  path: '/dev/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdSettingsRouteRoute =
  WorkspacesWorkspaceIdSettingsRouteRouteImport.update({
    id: '/workspaces/$workspaceId/settings',
    path: '/workspaces/$workspaceId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdNotesIndexRoute =
  WorkspacesWorkspaceIdNotesIndexRouteImport.update({
    id: '/workspaces/$workspaceId/notes/',
    path: '/workspaces/$workspaceId/notes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdNotesNoteIdRoute =
  WorkspacesWorkspaceIdNotesNoteIdRouteImport.update({
    id: '/workspaces/$workspaceId/notes/$noteId',
    path: '/workspaces/$workspaceId/notes/$noteId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdSettingsDangerRoute =
  WorkspacesWorkspaceIdSettingsDangerRouteImport.update({
    id: '/danger',
    path: '/danger',
    getParentRoute: () => WorkspacesWorkspaceIdSettingsRouteRoute,
  } as any)
const WorkspacesWorkspaceIdSettingsGeneralRoute =
  WorkspacesWorkspaceIdSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => WorkspacesWorkspaceIdSettingsRouteRoute,
  } as any)
const WorkspacesWorkspaceIdSettingsMembersRoute =
  WorkspacesWorkspaceIdSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => WorkspacesWorkspaceIdSettingsRouteRoute,
  } as any)
const WorkspacesWorkspaceIdSettingsPublishRoute =
  WorkspacesWorkspaceIdSettingsPublishRouteImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => WorkspacesWorkspaceIdSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/danger': typeof SettingsDangerRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/storage/$': typeof StorageSplatRoute
  '/w/$slug': typeof WSlugRoute
  '/workspaces/new': typeof WorkspacesNewRoute
  '/notes/': typeof NotesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/workspaces/$workspaceId/settings': typeof WorkspacesWorkspaceIdSettingsRouteRouteWithChildren
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/dev/oauth/authorize': typeof DevOauthAuthorizeRoute
  '/workspaces/$workspaceId/notes/$noteId': typeof WorkspacesWorkspaceIdNotesNoteIdRoute
  '/workspaces/$workspaceId/settings/danger': typeof WorkspacesWorkspaceIdSettingsDangerRoute
  '/workspaces/$workspaceId/settings/general': typeof WorkspacesWorkspaceIdSettingsGeneralRoute
  '/workspaces/$workspaceId/settings/members': typeof WorkspacesWorkspaceIdSettingsMembersRoute
  '/workspaces/$workspaceId/settings/publish': typeof WorkspacesWorkspaceIdSettingsPublishRoute
  '/workspaces/$workspaceId/notes/': typeof WorkspacesWorkspaceIdNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/danger': typeof SettingsDangerRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/storage/$': typeof StorageSplatRoute
  '/w/$slug': typeof WSlugRoute
  '/workspaces/new': typeof WorkspacesNewRoute
  '/notes': typeof NotesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/workspaces/$workspaceId/settings': typeof WorkspacesWorkspaceIdSettingsRouteRouteWithChildren
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/dev/oauth/authorize': typeof DevOauthAuthorizeRoute
  '/workspaces/$workspaceId/notes/$noteId': typeof WorkspacesWorkspaceIdNotesNoteIdRoute
  '/workspaces/$workspaceId/settings/danger': typeof WorkspacesWorkspaceIdSettingsDangerRoute
  '/workspaces/$workspaceId/settings/general': typeof WorkspacesWorkspaceIdSettingsGeneralRoute
  '/workspaces/$workspaceId/settings/members': typeof WorkspacesWorkspaceIdSettingsMembersRoute
  '/workspaces/$workspaceId/settings/publish': typeof WorkspacesWorkspaceIdSettingsPublishRoute
  '/workspaces/$workspaceId/notes': typeof WorkspacesWorkspaceIdNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/danger': typeof SettingsDangerRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/storage/$': typeof StorageSplatRoute
  '/w/$slug': typeof WSlugRoute
  '/workspaces/new': typeof WorkspacesNewRoute
  '/notes/': typeof NotesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/workspaces/$workspaceId/settings': typeof WorkspacesWorkspaceIdSettingsRouteRouteWithChildren
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/dev/oauth/authorize': typeof DevOauthAuthorizeRoute
  '/workspaces/$workspaceId/notes/$noteId': typeof WorkspacesWorkspaceIdNotesNoteIdRoute
  '/workspaces/$workspaceId/settings/danger': typeof WorkspacesWorkspaceIdSettingsDangerRoute
  '/workspaces/$workspaceId/settings/general': typeof WorkspacesWorkspaceIdSettingsGeneralRoute
  '/workspaces/$workspaceId/settings/members': typeof WorkspacesWorkspaceIdSettingsMembersRoute
  '/workspaces/$workspaceId/settings/publish': typeof WorkspacesWorkspaceIdSettingsPublishRoute
  '/workspaces/$workspaceId/notes/': typeof WorkspacesWorkspaceIdNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/privacy'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/invitations/$token'
    | '/notes/$noteId'
    | '/settings/auth'
    | '/settings/danger'
    | '/settings/profile'
    | '/settings/usage'
    | '/storage/$'
    | '/w/$slug'
    | '/workspaces/new'
    | '/notes/'
    | '/settings/'
    | '/workspaces/$workspaceId/settings'
    | '/auth/callback/$provider'
    | '/dev/oauth/authorize'
    | '/workspaces/$workspaceId/notes/$noteId'
    | '/workspaces/$workspaceId/settings/danger'
    | '/workspaces/$workspaceId/settings/general'
    | '/workspaces/$workspaceId/settings/members'
    | '/workspaces/$workspaceId/settings/publish'
    | '/workspaces/$workspaceId/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/invitations/$token'
    | '/notes/$noteId'
    | '/settings/auth'
    | '/settings/danger'
    | '/settings/profile'
    | '/settings/usage'
    | '/storage/$'
    | '/w/$slug'
    | '/workspaces/new'
    | '/notes'
    | '/settings'
    | '/workspaces/$workspaceId/settings'
    | '/auth/callback/$provider'
    | '/dev/oauth/authorize'
    | '/workspaces/$workspaceId/notes/$noteId'
    | '/workspaces/$workspaceId/settings/danger'
    | '/workspaces/$workspaceId/settings/general'
    | '/workspaces/$workspaceId/settings/members'
    | '/workspaces/$workspaceId/settings/publish'
    | '/workspaces/$workspaceId/notes'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/privacy'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/invitations/$token'
    | '/notes/$noteId'
    | '/settings/auth'
    | '/settings/danger'
    | '/settings/profile'
    | '/settings/usage'
    | '/storage/$'
    | '/w/$slug'
    | '/workspaces/new'
    | '/notes/'
    | '/settings/'
    | '/workspaces/$workspaceId/settings'
    | '/auth/callback/$provider'
    | '/dev/oauth/authorize'
    | '/workspaces/$workspaceId/notes/$noteId'
    | '/workspaces/$workspaceId/settings/danger'
    | '/workspaces/$workspaceId/settings/general'
    | '/workspaces/$workspaceId/settings/members'
    | '/workspaces/$workspaceId/settings/publish'
    | '/workspaces/$workspaceId/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  InvitationsTokenRoute: typeof InvitationsTokenRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  StorageSplatRoute: typeof StorageSplatRoute
  WSlugRoute: typeof WSlugRoute
  WorkspacesNewRoute: typeof WorkspacesNewRoute
  NotesIndexRoute: typeof NotesIndexRoute
  WorkspacesWorkspaceIdSettingsRouteRoute: typeof WorkspacesWorkspaceIdSettingsRouteRouteWithChildren
  AuthCallbackProviderRoute: typeof AuthCallbackProviderRoute
  DevOauthAuthorizeRoute: typeof DevOauthAuthorizeRoute
  WorkspacesWorkspaceIdNotesNoteIdRoute: typeof WorkspacesWorkspaceIdNotesNoteIdRoute
  WorkspacesWorkspaceIdNotesIndexRoute: typeof WorkspacesWorkspaceIdNotesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$token': {
      id: '/invitations/$token'
      path: '/invitations/$token'
      fullPath: '/invitations/$token'
      preLoaderRoute: typeof InvitationsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/auth': {
      id: '/settings/auth'
      path: '/auth'
      fullPath: '/settings/auth'
      preLoaderRoute: typeof SettingsAuthRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/danger': {
      id: '/settings/danger'
      path: '/danger'
      fullPath: '/settings/danger'
      preLoaderRoute: typeof SettingsDangerRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/usage': {
      id: '/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof SettingsUsageRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/storage/$': {
      id: '/storage/$'
      path: '/storage/$'
      fullPath: '/storage/$'
      preLoaderRoute: typeof StorageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug': {
      id: '/w/$slug'
      path: '/w/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof WSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/new': {
      id: '/workspaces/new'
      path: '/workspaces/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof WorkspacesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/$provider': {
      id: '/auth/callback/$provider'
      path: '/auth/callback/$provider'
      fullPath: '/auth/callback/$provider'
      preLoaderRoute: typeof AuthCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/oauth/authorize': {
      id: '/dev/oauth/authorize'
      path: '/dev/oauth/authorize'
      fullPath: '/dev/oauth/authorize'
      preLoaderRoute: typeof DevOauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId/settings': {
      id: '/workspaces/$workspaceId/settings'
      path: '/workspaces/$workspaceId/settings'
      fullPath: '/workspaces/$workspaceId/settings'
      preLoaderRoute: typeof WorkspacesWorkspaceIdSettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId/notes/': {
      id: '/workspaces/$workspaceId/notes/'
      path: '/workspaces/$workspaceId/notes'
      fullPath: '/workspaces/$workspaceId/notes/'
      preLoaderRoute: typeof WorkspacesWorkspaceIdNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId/notes/$noteId': {
      id: '/workspaces/$workspaceId/notes/$noteId'
      path: '/workspaces/$workspaceId/notes/$noteId'
      fullPath: '/workspaces/$workspaceId/notes/$noteId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdNotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId/settings/danger': {
      id: '/workspaces/$workspaceId/settings/danger'
      path: '/danger'
      fullPath: '/workspaces/$workspaceId/settings/danger'
      preLoaderRoute: typeof WorkspacesWorkspaceIdSettingsDangerRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdSettingsRouteRoute
    }
    '/workspaces/$workspaceId/settings/general': {
      id: '/workspaces/$workspaceId/settings/general'
      path: '/general'
      fullPath: '/workspaces/$workspaceId/settings/general'
      preLoaderRoute: typeof WorkspacesWorkspaceIdSettingsGeneralRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdSettingsRouteRoute
    }
    '/workspaces/$workspaceId/settings/members': {
      id: '/workspaces/$workspaceId/settings/members'
      path: '/members'
      fullPath: '/workspaces/$workspaceId/settings/members'
      preLoaderRoute: typeof WorkspacesWorkspaceIdSettingsMembersRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdSettingsRouteRoute
    }
    '/workspaces/$workspaceId/settings/publish': {
      id: '/workspaces/$workspaceId/settings/publish'
      path: '/publish'
      fullPath: '/workspaces/$workspaceId/settings/publish'
      preLoaderRoute: typeof WorkspacesWorkspaceIdSettingsPublishRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdSettingsRouteRoute
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsAuthRoute: typeof SettingsAuthRoute
  SettingsDangerRoute: typeof SettingsDangerRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsUsageRoute: typeof SettingsUsageRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAuthRoute: SettingsAuthRoute,
  SettingsDangerRoute: SettingsDangerRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsUsageRoute: SettingsUsageRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface WorkspacesWorkspaceIdSettingsRouteRouteChildren {
  WorkspacesWorkspaceIdSettingsDangerRoute: typeof WorkspacesWorkspaceIdSettingsDangerRoute
  WorkspacesWorkspaceIdSettingsGeneralRoute: typeof WorkspacesWorkspaceIdSettingsGeneralRoute
  WorkspacesWorkspaceIdSettingsMembersRoute: typeof WorkspacesWorkspaceIdSettingsMembersRoute
  WorkspacesWorkspaceIdSettingsPublishRoute: typeof WorkspacesWorkspaceIdSettingsPublishRoute
}

const WorkspacesWorkspaceIdSettingsRouteRouteChildren: WorkspacesWorkspaceIdSettingsRouteRouteChildren =
  {
    WorkspacesWorkspaceIdSettingsDangerRoute:
      WorkspacesWorkspaceIdSettingsDangerRoute,
    WorkspacesWorkspaceIdSettingsGeneralRoute:
      WorkspacesWorkspaceIdSettingsGeneralRoute,
    WorkspacesWorkspaceIdSettingsMembersRoute:
      WorkspacesWorkspaceIdSettingsMembersRoute,
    WorkspacesWorkspaceIdSettingsPublishRoute:
      WorkspacesWorkspaceIdSettingsPublishRoute,
  }

const WorkspacesWorkspaceIdSettingsRouteRouteWithChildren =
  WorkspacesWorkspaceIdSettingsRouteRoute._addFileChildren(
    WorkspacesWorkspaceIdSettingsRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  InvitationsTokenRoute: InvitationsTokenRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  StorageSplatRoute: StorageSplatRoute,
  WSlugRoute: WSlugRoute,
  WorkspacesNewRoute: WorkspacesNewRoute,
  NotesIndexRoute: NotesIndexRoute,
  WorkspacesWorkspaceIdSettingsRouteRoute:
    WorkspacesWorkspaceIdSettingsRouteRouteWithChildren,
  AuthCallbackProviderRoute: AuthCallbackProviderRoute,
  DevOauthAuthorizeRoute: DevOauthAuthorizeRoute,
  WorkspacesWorkspaceIdNotesNoteIdRoute: WorkspacesWorkspaceIdNotesNoteIdRoute,
  WorkspacesWorkspaceIdNotesIndexRoute: WorkspacesWorkspaceIdNotesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
